services:
  app:
    image: flask-api
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    ports:
      - 5000:5000
    networks:
      - app-net

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD-SHELL","redis-cli --raw incr ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      - app-net

networks:
  app-net:



